title: Gwen[Tastic]'s Twee File Splitter
show_downloads: true
show_projectgit: false
owner_name: "{Gwen[♡].Tastic}"
page_version: 1.3.7
app_version: 1.0.4
google_analytics: false
theme: jekyll-theme-dinky