title: Gwen[Tastic]'s Twee File Splitter
show_downloads: true
show_projectgit: false
owner_name: "{Gwen[♡].Tastic}"
page_version: 1.1.8
app_version: 1.0.1
google_analytics: true
theme: jekyll-theme-dinky